dependencies:
  # - <organization/repo>@<version>
  #- smartcontractkit/chainlink-brownie-contracts@1.1.1
  #- OpenZeppelin/openzeppelin-contracts@3.4.0
  - OpenZeppelin/openzeppelin-contracts@4.8.0
compiler:
  solc:
    version: 0.8.28
    versions:
      - 0.8.28
      - 0.6.12
    remappings:
      #- "@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1"
      #- "@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.4.0"
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.8.0"
    optimizer:
      enabled: true
      runs: 200
dotenv: .env
networks:
  default: development
  goerli:
    eth_usd_price_feed: "0xD4a33860578De61DBAbDc8BFdb98FD742fA7028e"
    verify: True
  mainnet-fork-dev:
    eth_usd_price_feed: "0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419"
    verify: False
  development:
    verify: False
  fl-local:
    verify: False
wallets:
  from_key: ${PRIVATE_KEY}